# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='书名')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('author_name', models.CharField(default='x', max_length=200, verbose_name='作者名')),
                ('age', models.IntegerField(blank=True, default=24, null=True, verbose_name='年龄')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('publication_date', models.DateField(verbose_name='出版时间')),
                ('website', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('summary', models.CharField(max_length=300, verbose_name='简介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='图片')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
    ]
